apiVersion: v1
kind: Service
metadata:
  name: photo-api-service
spec:
  selector:
    app: photo-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30896
  type: LoadBalancer
